language: python
sudo: required
group: deprecated-2017Q4
compiler:
  - clang
env:
  - PYTHON_VERSION=3.5
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing Qiita in it's own environment python2.7
  - travis_retry conda create --quiet --yes -n qiita python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme coveralls ipython[all]==2.4.1
  - pip install https://github.com/biocore/qiita/archive/master.zip --process-dependency-links
  - sed 's/PORT = 7777/PORT = 6379/g' $HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test.cfg
  - qiita-env make --no-load-ontologies
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  - source deactivate
  # installing this plugin
  - conda create --yes --quiet -n qiime2 --file https://data.qiime2.org/distro/core/qiime2-2017.9-conda-linux-64.txt
  - source activate qiime2
  - conda install --yes --quiet -n qiime2 -c anaconda flake8
  - conda install --yes --quiet -c conda-forge hdf5 h5py
  - pip install coveralls
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  # we are gonna use the same qiime2 environmen to install qtp-diversity
  - pip install https://github.com/qiita-spots/qtp-diversity/archive/master.zip
  - configure_diversity_types --env-script "source activate qiime2" --server-cert $QIITA_SERVER_CERT
  # we are gonna use the same qiime2 environmen to install qtp-visualization
  - pip install https://github.com/qiita-spots/qtp-visualization/archive/master.zip
  - configure_visualization_types --env-script "source activate qiime2" --server-cert $QIITA_SERVER_CERT
  - travis_retry pip install .
before_script:
  - source activate qiita
  - qiita plugins update
  - qiita pet webserver --no-build-docs start --master &
  - sleep 10 # give enough time to the webserver to start
script:
  - source activate qiime2
  - configure_qiime2 --env-script "source activate qiime2" --server-cert $QIITA_SERVER_CERT
  # Let's try registering the qtp-diversity types plugin manually:
  - start_diversity_types https://localhost:21174 register ignored
  - start_visualization_types https://localhost:21174 register ignored
  # Remove the SubjectAltNameWarning from the output
  - export PYTHONWARNINGS="ignore:Certificate for localhost has no \`subjectAltName\`"
  - nosetests --with-doctest --with-coverage --cover-package=qp_qiime2
  - flake8 qp_qiime2 setup.py scripts
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - coveralls
